// lib/emojis.js — Banco de emojis curados estilo WhatsApp
// Cada emoji tiene: char, category, names (ES) para búsqueda

(function () {
  const C = [
    // ============ CARITAS ============
    { c: '😀', cat: 'smileys', n: ['feliz', 'sonrisa', 'cara feliz', 'smile'] },
    { c: '😃', cat: 'smileys', n: ['feliz', 'sonrisa', 'ojos grandes'] },
    { c: '😄', cat: 'smileys', n: ['feliz', 'sonrisa', 'risa', 'ojos risa'] },
    { c: '😁', cat: 'smileys', n: ['feliz', 'sonrisa', 'dientes'] },
    { c: '😆', cat: 'smileys', n: ['risa', 'XD', 'cerrado ojos'] },
    { c: '😅', cat: 'smileys', n: ['sudor', 'nervios', 'sonrisa'] },
    { c: '🤣', cat: 'smileys', n: ['risa', 'suelo', 'carcajada'] },
    { c: '😂', cat: 'smileys', n: ['llorando risa', 'risa', 'lágrima'] },
    { c: '🙂', cat: 'smileys', n: ['leve sonrisa', 'suave'] },
    { c: '🙃', cat: 'smileys', n: ['boca abajo', 'ironia'] },
    { c: '😉', cat: 'smileys', n: ['guiño', 'coqueto', 'wink'] },
    { c: '😊', cat: 'smileys', n: ['sonrisa', 'tímido', 'feliz'] },
    { c: '😇', cat: 'smileys', n: ['ángel', 'inocente', 'halo'] },
    { c: '🥰', cat: 'smileys', n: ['enamorado', 'cariñoso', 'corazones'] },
    { c: '😍', cat: 'smileys', n: ['enamorado', 'ojos corazón', 'enamorada'] },
    { c: '🤩', cat: 'smileys', n: ['estrellas', 'emocionado', 'wow'] },
    { c: '😘', cat: 'smileys', n: ['beso', 'amor', 'kiss'] },
    { c: '😗', cat: 'smileys', n: ['beso', 'kiss'] },
    { c: '😚', cat: 'smileys', n: ['beso tímido', 'kiss'] },
    { c: '😙', cat: 'smileys', n: ['beso', 'kiss'] },
    { c: '🥺', cat: 'smileys', n: ['ojitos', 'rogando', 'por favor'] },
    { c: '🤔', cat: 'smileys', n: ['pensando', 'duda'] },
    { c: '🤤', cat: 'smileys', n: ['baboso', 'deseo'] },
    { c: '😏', cat: 'smileys', n: ['pícaro', 'sutil', 'smirk'] },
    { c: '😎', cat: 'smileys', n: ['lentes', 'cool'] },
    { c: '🥳', cat: 'smileys', n: ['fiesta', 'celebración'] },
    { c: '😴', cat: 'smileys', n: ['dormido', 'sleeping', 'sueño'] },
    { c: '🤐', cat: 'smileys', n: ['zipper', 'boca cerrada', 'secreto'] },
    { c: '😪', cat: 'smileys', n: ['dormido', 'cansado'] },
    { c: '😜', cat: 'smileys', n: ['lengua', 'guiño', 'play'] },
    { c: '🤪', cat: 'smileys', n: ['loco', 'zany'] },
    { c: '😝', cat: 'smileys', n: ['lengua', 'cerrados'] },
    { c: '🤑', cat: 'smileys', n: ['dinero', 'lengua'] },
    { c: '🤗', cat: 'smileys', n: ['abrazo', 'hug'] },
    { c: '🤭', cat: 'smileys', n: ['tapando boca', 'secreto'] },
    { c: '🤫', cat: 'smileys', n: ['silencio', 'shh', 'shush'] },
    { c: '🤥', cat: 'smileys', n: ['mentiroso'] },
    { c: '😶', cat: 'smileys', n: ['sin boca', 'silencio'] },
    { c: '😐', cat: 'smileys', n: ['neutral', 'serio'] },
    { c: '😑', cat: 'smileys', n: ['sin expresión'] },
    { c: '🙄', cat: 'smileys', n: ['ojos arriba', 'fastidio'] },
    { c: '😬', cat: 'smileys', n: ['mueca', 'nervios'] },
    { c: '😮', cat: 'smileys', n: ['boca abierta', 'sorprendido'] },
    { c: '😯', cat: 'smileys', n: ['asombrado'] },
    { c: '😲', cat: 'smileys', n: ['asombrado', 'shocked'] },
    { c: '😳', cat: 'smileys', n: ['sonrojado', 'rubor'] },
    { c: '🥵', cat: 'smileys', n: ['calor', 'sudor'] },
    { c: '🥶', cat: 'smileys', n: ['frío', 'helado'] },
    { c: '😱', cat: 'smileys', n: ['grito', 'miedo'] },
    { c: '😨', cat: 'smileys', n: ['miedo'] },
    { c: '😰', cat: 'smileys', n: ['angustia', 'sudor'] },
    { c: '😢', cat: 'smileys', n: ['llorando', 'triste'] },
    { c: '😭', cat: 'smileys', n: ['llorando mucho', 'llanto'] },
    { c: '😤', cat: 'smileys', n: ['enfado', 'resoplido'] },
    { c: '😡', cat: 'smileys', n: ['enojado', 'furioso'] },
    { c: '😠', cat: 'smileys', n: ['enojado'] },
    { c: '🤬', cat: 'smileys', n: ['palabrotas', 'furioso'] },
    { c: '😈', cat: 'smileys', n: ['diablito'] },
    { c: '👿', cat: 'smileys', n: ['diablo', 'enojado'] },
    { c: '💀', cat: 'smileys', n: ['calavera', 'muerte'] },
    { c: '💩', cat: 'smileys', n: ['caca', 'poop'] },
    { c: '🤡', cat: 'smileys', n: ['payaso'] },

    // ============ CORAZONES ============
    { c: '❤️', cat: 'hearts', n: ['corazón', 'rojo', 'love', 'amor'] },
    { c: '🧡', cat: 'hearts', n: ['corazón', 'naranja'] },
    { c: '💛', cat: 'hearts', n: ['corazón', 'amarillo'] },
    { c: '💚', cat: 'hearts', n: ['corazón', 'verde'] },
    { c: '💙', cat: 'hearts', n: ['corazón', 'azul'] },
    { c: '💜', cat: 'hearts', n: ['corazón', 'violeta', 'morado'] },
    { c: '🖤', cat: 'hearts', n: ['corazón', 'negro'] },
    { c: '🤍', cat: 'hearts', n: ['corazón', 'blanco'] },
    { c: '🤎', cat: 'hearts', n: ['corazón', 'marrón'] },
    { c: '💔', cat: 'hearts', n: ['corazón', 'roto'] },
    { c: '❣️', cat: 'hearts', n: ['exclamación', 'corazón'] },
    { c: '💕', cat: 'hearts', n: ['dos corazones'] },
    { c: '💞', cat: 'hearts', n: ['corazones', 'girando'] },
    { c: '💓', cat: 'hearts', n: ['corazón', 'latido'] },
    { c: '💗', cat: 'hearts', n: ['corazón', 'creciendo'] },
    { c: '💖', cat: 'hearts', n: ['corazón', 'brillo'] },
    { c: '💘', cat: 'hearts', n: ['cupido', 'flecha'] },
    { c: '💝', cat: 'hearts', n: ['regalo', 'corazón'] },
    { c: '💟', cat: 'hearts', n: ['decoración', 'corazón'] },
    { c: '♥️', cat: 'hearts', n: ['corazón', 'palo'] },
    { c: '💌', cat: 'hearts', n: ['carta', 'amor'] },

    // ============ PERSONAS / GESTOS ============
    { c: '👋', cat: 'people', n: ['hola', 'mano', 'saludo', 'wave'] },
    { c: '🤚', cat: 'people', n: ['mano', 'parada', 'stop'] },
    { c: '✋', cat: 'people', n: ['mano', 'parada', 'high five'] },
    { c: '🖐️', cat: 'people', n: ['mano', 'dedos'] },
    { c: '👌', cat: 'people', n: ['ok', 'perfecto'] },
    { c: '✌️', cat: 'people', n: ['paz', 'victoria'] },
    { c: '🤞', cat: 'people', n: ['dedos cruzados', 'suerte'] },
    { c: '🤟', cat: 'people', n: ['love you', 'te amo'] },
    { c: '🤘', cat: 'people', n: ['rock', 'cuernos'] },
    { c: '🤙', cat: 'people', n: ['llámame', 'call'] },
    { c: '👈', cat: 'people', n: ['izquierda', 'señalar'] },
    { c: '👉', cat: 'people', n: ['derecha', 'señalar'] },
    { c: '👆', cat: 'people', n: ['arriba', 'señalar'] },
    { c: '👇', cat: 'people', n: ['abajo', 'señalar'] },
    { c: '☝️', cat: 'people', n: ['arriba', 'uno'] },
    { c: '👍', cat: 'people', n: ['pulgar', 'like', 'ok', 'bien'] },
    { c: '👎', cat: 'people', n: ['pulgar abajo', 'mal'] },
    { c: '✊', cat: 'people', n: ['puño', 'fuerza'] },
    { c: '👊', cat: 'people', n: ['puño', 'golpe'] },
    { c: '👏', cat: 'people', n: ['aplauso', 'bravo'] },
    { c: '🙌', cat: 'people', n: ['celebración', 'manos arriba'] },
    { c: '👐', cat: 'people', n: ['manos abiertas'] },
    { c: '🤝', cat: 'people', n: ['apretón', 'acuerdo'] },
    { c: '🙏', cat: 'people', n: ['por favor', 'gracias', 'rezar'] },
    { c: '✍️', cat: 'people', n: ['escribiendo'] },
    { c: '💪', cat: 'people', n: ['músculo', 'fuerza', 'flex'] },
    { c: '🦵', cat: 'people', n: ['pierna'] },
    { c: '🦶', cat: 'people', n: ['pie'] },
    { c: '👂', cat: 'people', n: ['oído', 'oreja'] },
    { c: '👃', cat: 'people', n: ['nariz'] },
    { c: '👀', cat: 'people', n: ['ojos', 'mirada'] },
    { c: '👁️', cat: 'people', n: ['ojo'] },
    { c: '👅', cat: 'people', n: ['lengua'] },
    { c: '👄', cat: 'people', n: ['boca', 'labios'] },
    { c: '💋', cat: 'people', n: ['beso', 'labios', 'kiss'] },

    // ============ ANIMALES ============
    { c: '🐶', cat: 'animals', n: ['perro', 'cachorro', 'dog'] },
    { c: '🐱', cat: 'animals', n: ['gato', 'cat'] },
    { c: '🐭', cat: 'animals', n: ['ratón'] },
    { c: '🐹', cat: 'animals', n: ['hámster'] },
    { c: '🐰', cat: 'animals', n: ['conejo'] },
    { c: '🦊', cat: 'animals', n: ['zorro'] },
    { c: '🐻', cat: 'animals', n: ['oso'] },
    { c: '🐼', cat: 'animals', n: ['panda'] },
    { c: '🐨', cat: 'animals', n: ['koala'] },
    { c: '🐯', cat: 'animals', n: ['tigre'] },
    { c: '🦁', cat: 'animals', n: ['león'] },
    { c: '🐮', cat: 'animals', n: ['vaca'] },
    { c: '🐷', cat: 'animals', n: ['cerdo'] },
    { c: '🐸', cat: 'animals', n: ['rana'] },
    { c: '🐵', cat: 'animals', n: ['mono'] },
    { c: '🙈', cat: 'animals', n: ['mono no ve', 'vergüenza'] },
    { c: '🙉', cat: 'animals', n: ['mono no oye'] },
    { c: '🙊', cat: 'animals', n: ['mono no habla'] },
    { c: '🐔', cat: 'animals', n: ['gallina', 'pollo'] },
    { c: '🐧', cat: 'animals', n: ['pingüino'] },
    { c: '🐦', cat: 'animals', n: ['pájaro'] },
    { c: '🐤', cat: 'animals', n: ['pollito'] },
    { c: '🦆', cat: 'animals', n: ['pato'] },
    { c: '🦅', cat: 'animals', n: ['águila'] },
    { c: '🦉', cat: 'animals', n: ['búho'] },
    { c: '🦄', cat: 'animals', n: ['unicornio'] },
    { c: '🐝', cat: 'animals', n: ['abeja'] },
    { c: '🦋', cat: 'animals', n: ['mariposa'] },
    { c: '🐌', cat: 'animals', n: ['caracol'] },
    { c: '🐞', cat: 'animals', n: ['mariquita'] },
    { c: '🐢', cat: 'animals', n: ['tortuga'] },
    { c: '🐍', cat: 'animals', n: ['serpiente'] },
    { c: '🦖', cat: 'animals', n: ['dinosaurio'] },
    { c: '🐙', cat: 'animals', n: ['pulpo'] },
    { c: '🦀', cat: 'animals', n: ['cangrejo'] },
    { c: '🐠', cat: 'animals', n: ['pez'] },
    { c: '🐬', cat: 'animals', n: ['delfín'] },
    { c: '🐳', cat: 'animals', n: ['ballena'] },

    // ============ COMIDA ============
    { c: '🍎', cat: 'food', n: ['manzana', 'apple'] },
    { c: '🍐', cat: 'food', n: ['pera'] },
    { c: '🍊', cat: 'food', n: ['naranja', 'mandarina'] },
    { c: '🍋', cat: 'food', n: ['limón'] },
    { c: '🍌', cat: 'food', n: ['banana', 'plátano'] },
    { c: '🍉', cat: 'food', n: ['sandía'] },
    { c: '🍇', cat: 'food', n: ['uvas'] },
    { c: '🍓', cat: 'food', n: ['frutilla', 'fresa'] },
    { c: '🍒', cat: 'food', n: ['cereza'] },
    { c: '🍑', cat: 'food', n: ['durazno', 'melocotón', 'peach'] },
    { c: '🥭', cat: 'food', n: ['mango'] },
    { c: '🍍', cat: 'food', n: ['piña', 'ananá'] },
    { c: '🥥', cat: 'food', n: ['coco'] },
    { c: '🥝', cat: 'food', n: ['kiwi'] },
    { c: '🍅', cat: 'food', n: ['tomate'] },
    { c: '🍆', cat: 'food', n: ['berenjena'] },
    { c: '🥑', cat: 'food', n: ['palta', 'aguacate'] },
    { c: '🥦', cat: 'food', n: ['brócoli'] },
    { c: '🌶️', cat: 'food', n: ['chile', 'ají', 'picante'] },
    { c: '🌽', cat: 'food', n: ['maíz', 'choclo'] },
    { c: '🥕', cat: 'food', n: ['zanahoria'] },
    { c: '🧀', cat: 'food', n: ['queso'] },
    { c: '🍳', cat: 'food', n: ['huevo', 'desayuno'] },
    { c: '🥞', cat: 'food', n: ['panqueques'] },
    { c: '🥓', cat: 'food', n: ['panceta', 'bacon'] },
    { c: '🍔', cat: 'food', n: ['hamburguesa'] },
    { c: '🍟', cat: 'food', n: ['papas fritas'] },
    { c: '🍕', cat: 'food', n: ['pizza'] },
    { c: '🌭', cat: 'food', n: ['hot dog'] },
    { c: '🥪', cat: 'food', n: ['sándwich'] },
    { c: '🌮', cat: 'food', n: ['taco'] },
    { c: '🥗', cat: 'food', n: ['ensalada'] },
    { c: '🍝', cat: 'food', n: ['pasta', 'fideos'] },
    { c: '🍜', cat: 'food', n: ['ramen'] },
    { c: '🍣', cat: 'food', n: ['sushi'] },
    { c: '🍤', cat: 'food', n: ['camarón'] },
    { c: '🍙', cat: 'food', n: ['arroz'] },
    { c: '🍚', cat: 'food', n: ['arroz'] },
    { c: '🍦', cat: 'food', n: ['helado'] },
    { c: '🍧', cat: 'food', n: ['helado'] },
    { c: '🍨', cat: 'food', n: ['helado'] },
    { c: '🍰', cat: 'food', n: ['torta', 'pastel'] },
    { c: '🎂', cat: 'food', n: ['cumpleaños', 'torta'] },
    { c: '🍮', cat: 'food', n: ['flan'] },
    { c: '🍭', cat: 'food', n: ['caramelo', 'paleta'] },
    { c: '🍬', cat: 'food', n: ['caramelo'] },
    { c: '🍫', cat: 'food', n: ['chocolate'] },
    { c: '🍿', cat: 'food', n: ['pochoclo', 'palomitas'] },
    { c: '🍩', cat: 'food', n: ['dona'] },
    { c: '🍪', cat: 'food', n: ['galleta'] },
    { c: '🥛', cat: 'food', n: ['leche'] },
    { c: '☕', cat: 'food', n: ['café', 'coffee'] },
    { c: '🍵', cat: 'food', n: ['té'] },
    { c: '🍷', cat: 'food', n: ['vino'] },
    { c: '🍸', cat: 'food', n: ['cóctel'] },
    { c: '🍹', cat: 'food', n: ['trago', 'tropical'] },
    { c: '🍺', cat: 'food', n: ['cerveza'] },
    { c: '🍻', cat: 'food', n: ['cerveza', 'chinchín'] },
    { c: '🥂', cat: 'food', n: ['brindis'] },

    // ============ ACTIVIDADES ============
    { c: '⚽', cat: 'activities', n: ['fútbol', 'pelota'] },
    { c: '🏀', cat: 'activities', n: ['básquet'] },
    { c: '🏈', cat: 'activities', n: ['fútbol americano'] },
    { c: '⚾', cat: 'activities', n: ['béisbol'] },
    { c: '🎾', cat: 'activities', n: ['tenis'] },
    { c: '🏐', cat: 'activities', n: ['voley'] },
    { c: '🏉', cat: 'activities', n: ['rugby'] },
    { c: '🎱', cat: 'activities', n: ['pool', 'billar'] },
    { c: '🏓', cat: 'activities', n: ['ping pong'] },
    { c: '🏸', cat: 'activities', n: ['bádminton'] },
    { c: '🥊', cat: 'activities', n: ['boxeo'] },
    { c: '🥋', cat: 'activities', n: ['karate'] },
    { c: '🎮', cat: 'activities', n: ['videojuego', 'gaming'] },
    { c: '🎲', cat: 'activities', n: ['dado'] },
    { c: '🧩', cat: 'activities', n: ['puzzle'] },
    { c: '🎯', cat: 'activities', n: ['diana'] },
    { c: '🎳', cat: 'activities', n: ['bowling'] },
    { c: '🎤', cat: 'activities', n: ['micrófono', 'karaoke'] },
    { c: '🎧', cat: 'activities', n: ['auriculares', 'música'] },
    { c: '🎼', cat: 'activities', n: ['música', 'partitura'] },
    { c: '🎹', cat: 'activities', n: ['piano', 'teclado'] },
    { c: '🥁', cat: 'activities', n: ['tambor', 'batería'] },
    { c: '🎷', cat: 'activities', n: ['saxofón'] },
    { c: '🎺', cat: 'activities', n: ['trompeta'] },
    { c: '🎸', cat: 'activities', n: ['guitarra'] },
    { c: '🎻', cat: 'activities', n: ['violín'] },

    // ============ VIAJES ============
    { c: '🚗', cat: 'travel', n: ['auto', 'carro', 'coche'] },
    { c: '🚕', cat: 'travel', n: ['taxi'] },
    { c: '🚙', cat: 'travel', n: ['SUV', 'auto'] },
    { c: '🚌', cat: 'travel', n: ['colectivo', 'bus'] },
    { c: '🚎', cat: 'travel', n: ['colectivo'] },
    { c: '🏎️', cat: 'travel', n: ['carrera', 'F1'] },
    { c: '🚓', cat: 'travel', n: ['patrulla', 'policía'] },
    { c: '🚑', cat: 'travel', n: ['ambulancia'] },
    { c: '🚒', cat: 'travel', n: ['bomberos'] },
    { c: '🚐', cat: 'travel', n: ['van'] },
    { c: '🚚', cat: 'travel', n: ['camión'] },
    { c: '🚲', cat: 'travel', n: ['bicicleta', 'bici'] },
    { c: '🛵', cat: 'travel', n: ['moto', 'scooter'] },
    { c: '🏍️', cat: 'travel', n: ['moto'] },
    { c: '✈️', cat: 'travel', n: ['avión', 'vuelo'] },
    { c: '🚀', cat: 'travel', n: ['cohete', 'rocket'] },
    { c: '🛸', cat: 'travel', n: ['OVNI', 'platillo'] },
    { c: '🚁', cat: 'travel', n: ['helicóptero'] },
    { c: '⛵', cat: 'travel', n: ['velero', 'barco'] },
    { c: '🚤', cat: 'travel', n: ['lancha'] },
    { c: '🛳️', cat: 'travel', n: ['crucero'] },
    { c: '🚢', cat: 'travel', n: ['barco'] },
    { c: '⚓', cat: 'travel', n: ['ancla'] },
    { c: '🏖️', cat: 'travel', n: ['playa'] },
    { c: '🏝️', cat: 'travel', n: ['isla'] },
    { c: '🏜️', cat: 'travel', n: ['desierto'] },
    { c: '🌋', cat: 'travel', n: ['volcán'] },
    { c: '🏔️', cat: 'travel', n: ['montaña'] },
    { c: '🏕️', cat: 'travel', n: ['camping'] },
    { c: '🏠', cat: 'travel', n: ['casa'] },
    { c: '🏡', cat: 'travel', n: ['casa jardín'] },
    { c: '🏢', cat: 'travel', n: ['edificio', 'oficina'] },
    { c: '🏬', cat: 'travel', n: ['shopping'] },
    { c: '🏥', cat: 'travel', n: ['hospital'] },
    { c: '🏦', cat: 'travel', n: ['banco'] },
    { c: '🏨', cat: 'travel', n: ['hotel'] },
    { c: '🏫', cat: 'travel', n: ['escuela'] },
    { c: '🏰', cat: 'travel', n: ['castillo'] },

    // ============ OBJETOS ============
    { c: '⌚', cat: 'objects', n: ['reloj'] },
    { c: '📱', cat: 'objects', n: ['celular', 'móvil', 'teléfono'] },
    { c: '💻', cat: 'objects', n: ['laptop', 'computadora'] },
    { c: '⌨️', cat: 'objects', n: ['teclado'] },
    { c: '🖥️', cat: 'objects', n: ['computadora', 'monitor'] },
    { c: '🖨️', cat: 'objects', n: ['impresora'] },
    { c: '💾', cat: 'objects', n: ['disco'] },
    { c: '📷', cat: 'objects', n: ['cámara'] },
    { c: '📸', cat: 'objects', n: ['foto', 'cámara'] },
    { c: '📹', cat: 'objects', n: ['video', 'cámara'] },
    { c: '🎥', cat: 'objects', n: ['cine', 'cámara'] },
    { c: '📺', cat: 'objects', n: ['televisor', 'TV'] },
    { c: '📻', cat: 'objects', n: ['radio'] },
    { c: '☎️', cat: 'objects', n: ['teléfono'] },
    { c: '🔋', cat: 'objects', n: ['batería'] },
    { c: '🔌', cat: 'objects', n: ['enchufe'] },
    { c: '💡', cat: 'objects', n: ['bombilla', 'idea'] },
    { c: '🔦', cat: 'objects', n: ['linterna'] },
    { c: '🕯️', cat: 'objects', n: ['vela'] },
    { c: '💸', cat: 'objects', n: ['dinero volando'] },
    { c: '💵', cat: 'objects', n: ['dinero', 'billete'] },
    { c: '💰', cat: 'objects', n: ['dinero', 'bolsa'] },
    { c: '💳', cat: 'objects', n: ['tarjeta', 'crédito'] },
    { c: '💎', cat: 'objects', n: ['diamante', 'joya'] },
    { c: '🔧', cat: 'objects', n: ['llave', 'herramienta'] },
    { c: '🔨', cat: 'objects', n: ['martillo'] },
    { c: '🔑', cat: 'objects', n: ['llave'] },
    { c: '🚪', cat: 'objects', n: ['puerta'] },
    { c: '🪑', cat: 'objects', n: ['silla'] },
    { c: '🛋️', cat: 'objects', n: ['sofá'] },
    { c: '🛏️', cat: 'objects', n: ['cama'] },
    { c: '🎁', cat: 'objects', n: ['regalo'] },
    { c: '🎈', cat: 'objects', n: ['globo'] },
    { c: '🎉', cat: 'objects', n: ['fiesta', 'celebración'] },
    { c: '🎊', cat: 'objects', n: ['fiesta', 'confeti'] },
    { c: '🏆', cat: 'objects', n: ['trofeo', 'premio'] },
    { c: '🥇', cat: 'objects', n: ['medalla oro', 'primer lugar'] },
    { c: '🥈', cat: 'objects', n: ['medalla plata'] },
    { c: '🥉', cat: 'objects', n: ['medalla bronce'] },
    { c: '📚', cat: 'objects', n: ['libros'] },
    { c: '📖', cat: 'objects', n: ['libro'] },
    { c: '✏️', cat: 'objects', n: ['lápiz'] },
    { c: '📝', cat: 'objects', n: ['cuaderno', 'nota'] },
    { c: '📌', cat: 'objects', n: ['pin'] },
    { c: '📍', cat: 'objects', n: ['ubicación', 'pin'] },

    // ============ SÍMBOLOS ============
    { c: '✨', cat: 'symbols', n: ['destellos', 'sparkle', 'brillo'] },
    { c: '⭐', cat: 'symbols', n: ['estrella'] },
    { c: '🌟', cat: 'symbols', n: ['estrella brillante'] },
    { c: '💫', cat: 'symbols', n: ['mareo', 'estrella'] },
    { c: '🔥', cat: 'symbols', n: ['fuego', 'llama', 'fire'] },
    { c: '💥', cat: 'symbols', n: ['explosión', 'boom'] },
    { c: '💯', cat: 'symbols', n: ['100', 'perfecto'] },
    { c: '💬', cat: 'symbols', n: ['bocadillo', 'chat', 'comentario'] },
    { c: '💭', cat: 'symbols', n: ['pensamiento', 'burbuja'] },
    { c: '🗯️', cat: 'symbols', n: ['bocadillo enfado'] },
    { c: '♻️', cat: 'symbols', n: ['reciclar'] },
    { c: '✅', cat: 'symbols', n: ['check', 'hecho'] },
    { c: '❌', cat: 'symbols', n: ['cruz', 'no'] },
    { c: '❓', cat: 'symbols', n: ['pregunta'] },
    { c: '❗', cat: 'symbols', n: ['exclamación'] },
    { c: '⚠️', cat: 'symbols', n: ['advertencia'] },
    { c: '🚫', cat: 'symbols', n: ['prohibido'] },
    { c: '💤', cat: 'symbols', n: ['zzz', 'dormir'] },
    { c: '🎵', cat: 'symbols', n: ['música', 'nota'] },
    { c: '🎶', cat: 'symbols', n: ['música', 'notas'] },
    { c: '🌹', cat: 'symbols', n: ['rosa'] },
    { c: '🌷', cat: 'symbols', n: ['tulipán'] },
    { c: '🌸', cat: 'symbols', n: ['flor cerezo'] },
    { c: '💐', cat: 'symbols', n: ['ramo', 'flores'] },
    { c: '🌺', cat: 'symbols', n: ['flor'] },
    { c: '🌻', cat: 'symbols', n: ['girasol'] },
    { c: '🌼', cat: 'symbols', n: ['flor'] }
  ];

  // Flat list con búsqueda precomputada
  const ALL = C.map((e) => ({
    char: e.c,
    cat: e.cat,
    names: e.n,
    haystack: (e.c + ' ' + e.n.join(' ')).toLowerCase()
  }));

  const CATEGORIES = [
    { id: 'smileys',    icon: '😀', label: 'Caritas' },
    { id: 'hearts',     icon: '❤️', label: 'Corazones' },
    { id: 'people',     icon: '👋', label: 'Gestos' },
    { id: 'animals',    icon: '🐱', label: 'Animales' },
    { id: 'food',       icon: '🍎', label: 'Comida' },
    { id: 'activities', icon: '⚽', label: 'Actividades' },
    { id: 'travel',     icon: '🚗', label: 'Viajes' },
    { id: 'objects',    icon: '💡', label: 'Objetos' },
    { id: 'symbols',    icon: '✨', label: 'Símbolos' }
  ];

  function getCategory(id) {
    return ALL.filter((e) => e.cat === id).map((e) => e.char);
  }

  function search(query) {
    const q = query.toLowerCase().trim();
    if (!q) return [];
    return ALL.filter((e) => e.haystack.includes(q));
  }

  window.EmojiData = {
    ALL,
    CATEGORIES,
    getCategory,
    search
  };
})();